### ISSUE TITLE
Error : dbname.users doesn't exist

### ISSUE THREAD

**Issue by artlantis** [ci-blox/Ignition-Go#33]
Last step of the installation, Ignition-Go throwing the following error message :

```
Error Number: 1146
Table 'inventory.users' doesn't exist
```
When I check the related files, User_model.php has an insert method which is calling parent::insert function. Parent class, which is IGO_Model, has a protected $table_name property. This property has been set 'users' in User_Model.php.

**Comment by boblennes** [comment]
Is it because the install.sql file uses a table prefix of igo by default (so the table should be "inventory.igo_users") ? 
Long term, we really need to create the tables using migration(s) instead of a running a .sql file, but try using a prefix of igo_ OR otherwise change the igo_ to the desired prefix, and adjust the prefix in the config/database.php file.

**Comment by artlantis** [comment]
Thanks, I did it before. My intent was to inform you about the issue.
